package:
  name: smirnoff99frosst
  version: "1.0.6"

source:
    path: ../

build:
    noarch: python
    preserve_egg_dir: True
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
        - setuptools
    run:
        - python

about:
  home: https://github.com/openforcefield/smirnoff99Frosst
  license: MIT
  license_file: LICENSE
